export enum AuthError {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  COULD_NOT_FIND_USER = 'COULD_NOT_FIND_USER',
  COULD_NOT_CREATE_USER = 'COULD_NOT_CREATE_USER',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  COULD_NOT_UPDATE_PASSWORD = 'COULD_NOT_UPDATE_PASSWORD',

  COULD_NOT_GENERATE_TOKEN = 'COULD_NOT_GENERATE_TOKEN',
  COULD_NOT_INVALIDATE_REFRESH_TOKEN = 'COULD_NOT_INVALIDATE_REFRESH_TOKEN',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
}
