export enum BaseErrorsType {
  NOT_FOUND = 'NOT_FOUND',
  INCORRECT_DATA = 'INCORRECT_DATA',
  UNKNOWN = 'UNKNOWN',
  ALREADY_DONE = 'ALREADY_DONE',
  RETRY_LATER = 'RETRY_LATER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
}
